[package]
name = "resume-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
pdf-writer = "0.9"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
